#!/usr/bin/env bash

input_scps=$1
output_prefix=$2
wav_dir=$3

mkdir -p ./log

./make_mfcc_input_wav.py $input_scps $wav_dir	2>./log/make_mfcc_input_wav_err
for wav_id_dir in `echo $wav_dir/$(basename $input_scps)*`; do
    echo "BEFORE djt_mfcc: "$input_scps  - $wav_id_dir  : date-`date`
    ./psf_mfcc.py $input_scps $wav_id_dir   >"./log/djt_out_$(basename ${wav_id_dir})"  \
    #./djt_mfcc.sh $input_scps $wav_id_dir   >"./log/djt_out_$(basename ${wav_id_dir})"  \
                                            2>"./log/djt_err_$(basename ${wav_id_dir})"
    ./write_mfcc_scp_ark.py  $wav_id_dir ${output_prefix}_${wav_id_dir#*wav_}
done
